### PR TITLE
Perfect Dark Zero Touch Controls

### PR DESCRIPTION
**Pull request by Kode-Z**
Perfect Dark Zero

Custom touch controls for Perfect Dark Zero!

### CODE REVIEW

**Comment by redphx** [comment]
Don't edit the file directly on github.  

This guide might help: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by redphx** [comment]
Don't forget to [beautify the JSON](https://duckduckgo.com/?t=ffab&q=format+json&ia=answer) (indent = 2 spaces)

**Comment by Kode-Z** [comment]
It's valid!

**Comment by redphx** [comment]
I mean you need to copy the beautified code and save it into the file again.

**Comment by redphx** [comment]
Thanks!

**Pull request merged**
