### PR TITLE
Doom 3 Touch Controls

### PR DESCRIPTION
**Pull request by Kode-Z**
IMG_9763

Touch controls for DOOM 3.

### CODE REVIEW

**Comment by redphx** [comment]
Please include the screenshot of the game's control mapping so I don't have to look for it.

I don't like the current layout:  
- Two `weaponSelect` icons. I'd prefer showing button's icons.  
- The right side has too many buttons. If possible move some buttons to the left
- What does the dpad do?

**Comment by Kode-Z** [comment]
IMG_9761

Here are the controls (the dpad is for special weapons!)

**Comment by redphx** [comment]
The Fire and reload buttons are the most used buttons, so I'd recommend to place them at:
- Reload -> where the current crouch button is
- Fire -> where the current Y button is

I also don't like the placement of the B button. If it isn't being used much them put it to the top-right position where the Menu is.

**Comment by redphx** [comment]
- `layers.AimTouchpad` is not being used. If you don't use it, please remove it.  
- Also remove the `walk` and `look` icons
- I think the `deadzone` properties have no uses.

**Comment by redphx** [comment]
Thanks!

**Pull request merged**
